### ISSUE TITLE
Order of request headers should be preserved

### ISSUE THREAD

**Issue by AlessioCantina** [python-mechanize/mechanize#29]
Some sites can't be opened if request headers are in wrong order (it's probably a way to protect against automated tools like this one).
Right now setting headers with br.addheaders = headers doesn't guarantee the order of the headers as set (I checked it with Burp).

**Comment by AlessioCantina** [comment]
I would like to know if the issue doesn't exist and I misunderstood something or if you decided non to fix the issue.

**Comment by kovidgoyal** [comment]
It closed because it is already fixed.,

**Comment by AlessioCantina** [comment]
> It closed because it is already fixed.,

So can you explain me why this happen:
`br = mechanize.Browser() 
br.addheaders = [('Host', 'site.com'),
                 ('User-Agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:64.0) Gecko/20100101 Firefox/64.0'),
                  ('Accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'),
                  ('Accept-Language', 'it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3'),
                  ('Accept-Encoding', 'gzip, deflate')]
br.open(url)
`
The intercepted requests does not follow the order.
`GET / HTTP/1.1
Accept-Language: it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Host: jet.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:64.0) Gecko/20100101 Firefox/64.0
Connection: close`

I am using mechanize 0.3.7 on python 2.7

**Comment by kovidgoyal** [comment]
Umm it was just fixed a few hours ago by the commit which closed this
issue.

**Comment by kovidgoyal** [comment]
there you go: https://github.com/python-mechanize/mechanize/commit/fc6eba549989282410b6e6a8304b8b00685e9ad8

**Comment by AlessioCantina** [comment]
> there you go: [fc6eba5](https://github.com/python-mechanize/mechanize/commit/fc6eba549989282410b6e6a8304b8b00685e9ad8)

I am sorry but it's still not fixed, printing headers at line 1138 proves that Accept-Encoding is still at the first position, I think the problems come from the fact that req.headers should contain the host instead it contains Accept-Encoding

**Comment by kovidgoyal** [comment]
I just added a callback to allow users full control of headers sent with every request.
